//  Get all items 
GET http://127.0.0.1:5000/api/items  HTTP/1.1
content-type: application/json

###
//  Get all items where id more than half of the maxnumber.
GET http://127.0.0.1:5000/api/items/moreThan  HTTP/1.1
content-type: application/json

### 
//  Get some items
GET http://127.0.0.1:5000/api/items/someItems?brands=apple&brands=samsung&brands=dell  HTTP/1.1
content-type: application/json

###
// Delete some items
DELETE  http://127.0.0.1:5000/api/items/someItems?models=apple&models=iphone HTTP/1.1
content-type: application/json


### 
// Update some items 
PUT http://127.0.0.1:5000/api/items
content-type: application/json

 {
    "id": 14,
    "category": "Electronics",
    "type": "Laptops",
    "brand": "Samsung",
    "model": "MacBook Air",
    "price": "85264.00",
    "store": "ALLO",
    "amount": "1017"
  }