//  Get all stores 
GET http://127.0.0.1:5000/api/orders  HTTP/1.1
content-type: application/json

###
//  Get all stores where id more than half of the maxnumber.
GET http://127.0.0.1:5000/api/orders/moreThan  HTTP/1.1
content-type: application/json

### 
//  Get some stores
GET http://127.0.0.1:5000/api/orders/someOrders?orders=Smith&orders=Taylor  HTTP/1.1
content-type: application/json

###
// Delete some stores
DELETE  http://127.0.0.1:5000/api/orders/someOrders  HTTP/1.1
content-type: application/json


### 
// Update some stores 
PUT http://127.0.0.1:5000/api/orders  HTTP/1.1
content-type: application/json

{ 
  "code": 4,
  "date": "2024-08-01T22:45:48.212Z",
  "amount": 656,
  "paid": false,
  "customer": 5
}